name: publish
on:
  push:
    branches: [main]
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "yarn"
          registry-url: "https://registry.npmjs.org"
      - run: npm version --no-git-tag-version '1.0.0-${{ github.sha }}' && npm publish
        working-directory: packages/boilerplate
      - run: npm version --no-git-tag-version '1.0.0-${{ github.sha }}' && npm publish
        working-directory: packages/eslint-config
      - run: npm version --no-git-tag-version '1.0.0-${{ github.sha }}' && npm publish
        working-directory: packages/storybook
      - run: npm version --no-git-tag-version '1.0.0-${{ github.sha }}' && npm publish
        working-directory: packages/vite-react
